### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Rudloff**
Fix Markdown formatting

### CODE REVIEW

**Review by z3ntu — APPROVED** [review]
LGTM

**Review by Roboe — APPROVED** [review]
:+1:

**Comment by Rudloff** [comment]
(Out of curiosity, I built [@mudar's fork of the launcher](https://github.com/mudar/Fairphone/tree/master/FairphoneHome) and it surprinsigly still works on Android 6.)

**Comment by Roboe** [comment]
Changing wallpaper, included? :P
His Peace of Mind+ app looks great (if fact, that's why I arrived to the original Kwamecorp repo)

**Comment by Rudloff** [comment]
Yes! The app automatically gets the storage permission. (I think Android does that when an app uses a really old SDK version.)

**Comment by Roboe** [comment]
Oh! Yup, that's right.

**Pull request merged**
